max_vars(3).
max_body(3).
max_clauses(3).

modeh(f,2).
modeb(f,2).
modeb(at_top,1).
modeb(at_bottom,1).
modeb(at_left,1).
modeb(at_right,1).
modeb(move_left,2).
modeb(move_right,2).
modeb(move_up,2).
modeb(move_down,2).

direction(f,0,in).
direction(f,1,out).
direction(move_left,0,in).
direction(move_right,0,in).
direction(move_up,0,in).
direction(move_down,0,in).
direction(move_left,1,out).
direction(move_right,1,out).
direction(move_up,1,out).
direction(move_down,1,out).
direction(at_top,0,in).
direction(at_bottom,0,in).
direction(at_left,0,in).
direction(at_right,0,in).